language: node_js
node_js:
  - "7"
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  deploy:
    provider: firebase
    token:
      secure: $FIREBASE_TOKEN
    project: "megan-bailey-portfolio"